apiVersion: apps/v1 
kind: Deployment
metadata:
  name: chatbackend
spec:
  selector:
    matchLabels:
      app: chat
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: chat
        tier: backend
    spec:
      containers:
      - name: kubchatbackend
        image: maisoul/kubchatbackend:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 5000