apiVersion: v1
kind: Service
metadata:
  name: chatclient
  labels:
    app: chatclient
    tier: frontend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  # type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  ports:
  - port: 5001
    nodePort: 80
    protocol: TCP
    name: http
  - port: 5001
    nodePort: 443
    protocol: TCP
    name: https
  selector:
    app: chatclient
    tier: frontend
